Vagrant.configure("2") do |config|

  config.vm.define "gitlab_server" do |server|

    server.vm.box = "perk/ubuntu-2204-arm64"
    server.vm.hostname = "gitlab.server.local"

    server.vm.provider "qemu" do |qe|
      qe.ssh_port = "50023"
      qe.memory = 4096
      qe.cpus = 2
    end

 
    server.vm.synced_folder ".", "/vagrant", type: "rsync"


    server.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "/vagrant/playbooks/run.yml"
      ansible.tags = "install"
    end

  end

end
